# @package _group_
dataset:
  backbone: 
    _target_: src.data.batched_sequence_dataset.AnidanceSequenceDataset
  path: "./datasets/anidance/dances"
  name: "anidance"
  batch_size: 512
  num_workers: 0
  sequence_offset_train: 64
  min_sequence_length_train: 128
  max_sequence_length_train: 128
  sequence_offset_validation: 64
  sequence_length_validation: 128
  use_sliding_windows: true
backbone:
  _target_: src.motion.modules.zero_vel.ZeroVelocity
optimizer:
 _target_: torch.optim.Adam
scheduler:
 _target_: torch.optim.lr_scheduler.StepLR
trainer:
  max_epochs: 0
  min_epochs: 0