base_config: lafan_inbetween
parameters:
  model.logging.path: "./logs/lafan"
  model.logging.name: "ZeroVelocity"
  model.trainer.max_epochs: 0
  model.dataset.num_workers: 4
  model.dataset.batch_size: 2048
  model.dataset.centerXZ: True
  model.dataset.y_rotate_on_frame: 9
  model.dataset.mirror: False
  model.dataset.rotate: False
  model.dataset.augment_training: False
  model.dataset.augment_validation: True
  model.optimizer: None
  model.backbone._target_: src.modules.zero_vel.ZeroVelocityWrapper
  
  